[project]
name = "c64org-crawler"
version = "0.1.0"
description = "scrapes game files from the C64G.com website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
]
